apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaM0psWjJ0MWVtNWxkSE52ZGpFNU9UZzZaMmh3WHpGSFUwWkVTakI2VDNBNVFYbDBha2t3TW5seE1HdFBURzlrZHpSSVV6QjRiekZTYkE9PSIKICAgIH0KICB9LAogICJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0K
type: kubernetes.io/dockerconfigjson
